[run]
timeout = "15s"
allow-parallel-runners = true

[output]
format = "colored-line-number"

[linters]
disable-all = true
enable = [
    # Styling/formatting
    "gci",   # Handles import groups/ordering
    "gofmt",
]

[issues]
fix = true
exclude-use-default = false

[linters-settings.gci]
sections = ["standard", "default", "prefix(github.com/go-kivik/kivik/)"]
skip-generated = false
custom-order = true
